let data = {
  // <-------------------------------------------------------------------Computer---------------------------------------------------------------->

  collage_name: "L. E. Collage",
  department_data: [
    {
      department: "Computer",
      dep_head: "M.S. Dhoni",
      year: [
        {
          year: "First",
          year_head: "Devendra Thakor",
          student_data: [
            {
              id: "2022_1",
              student_name: "Vivek Bajaj",
              gender: "Male",
              contact_number: "9879870001",
              email_id: "vevekbajaj@gmail.com",
              admission_year: "2022",
              merit_12th: "76",
            },
            {
              id: "2022_2",
              student_name: "Shalini Patel",
              gender: "Female",
              contact_number: "9879870002",
              email_id: "pshalini@gmail.com",
              admission_year: "2022",
              merit_12th: "85",
            },
            {
              id: "2022_3",
              student_name: "Kevin jadeja",
              gender: "Male",
              contact_number: "9879870003",
              email_id: "kevin@gmail.com",
              admission_year: "2022",
              merit_12th: "87",
            },
            {
              id: "2022_4",
              student_name: "Harsh Dhorajiya",
              gender: "Male",
              contact_number: "9879870004",
              email_id: "Harsh22@gmail.com",
              admission_year: "2022",
              merit_12th: "83",
            },
            {
              id: "",
              student_name: "Vishal Gajera",
              gender: "Male",
              contact_number: "9835540004",
              email_id: "",
              admission_year: "2022",
              merit_12th: "93",
            },
          ],
        },

        // <-------------------------------------------------------------second year---------------------------------------------------------->
        {
          year: "Second",
          year_head: "Rachana Patel",
          student_data: [
            {
              id: "2021_1",
              student_name: "Divayesh Ranpara",
              gender: "Male",
              contact_number: "9879870005",
              email_id: "dr@gmail.com",
              admission_year: "2021",
              merit_12th: "78",
            },
            {
              id: "",
              student_name: "Yagnik Devani",
              gender: "Male",
              contact_number: "9879870008",
              email_id: "",
              admission_year: "2021",
              merit_12th: "88",
            },
            {
              id: "",
              student_name: "Ronak Koladiya",
              gender: "Male",
              contact_number: "9879870008",
              email_id: "",
              admission_year: "2021",
              merit_12th: "80",
            },
            {
              id: "2022_0_2",
              student_name: "Krunal Mehata",
              gender: "Male",
              contact_number: "9879870006",
              email_id: "Krunal23@gmail.com",
              admission_year: "2022",
              merit_diploma: "88",
            },
            {
              id: "2022_0_4",
              student_name: "Shubham Khunt",
              gender: "Male",
              contact_number: "9879870007",
              email_id: "shubhu7@gmail.com",
              admission_year: "2022",
              merit_diploma: "67",
            },
            {
              id: "",
              student_name: "Bhargav Gajera",
              gender: "Male",
              contact_number: "9835540004",
              email_id: "",
              admission_year: "2021",
              merit_12th: "93",
            },
            {
              id: "2021_2",
              student_name: "Ashwin Patel",
              gender: "Male",
              contact_number: "9879870008",
              email_id: "apatel@gmail.com",
              admission_year: "2021",
              merit_12th: "77",
            },
          ],
        },

        // <-------------------------------------------------------------third year----------------------------------------------------------->
        {
          year: "Third",
          year_head: "Niyanta Desai",
          student_data: [
            {
              id: "2021_0_1",
              student_name: "Chitranjan Rama",
              gender: "Male",
              contact_number: "9879870009",
              email_id: "c.r@gmail.com",
              admission_year: "2021",
              merit_diploma: "72",
            },
            {
              id: "2020_2",
              student_name: "Nupur Parmer",
              gender: "Female",
              contact_number: "9879870010",
              email_id: "np@gmail.com",
              admission_year: "2020",
              merit_12th: "77",
            },
            {
              id: "2020_3",
              student_name: "Sameera Rai",
              gender: "Female",
              contact_number: "9879870011",
              email_id: "sameera@gmail.com",
              admission_year: "2020",
              merit_12th: "88",
            },
            {
              id: "2020_4",
              student_name: "Prabhat Goda",
              gender: "Male",
              contact_number: "9879870012",
              email_id: "pg@gmail.com",
              admission_year: "2020",
              merit_12th: "65",
            },
            {
              id: "2021_0_2",
              student_name: "Vaishali Bhatt",
              gender: "Female",
              contact_number: "98798734011",
              email_id: "Vaishali_bhatt@gmail.com",
              admission_year: "2021",
              merit_diploma: "74",
            },
            {
              id: "",
              student_name: "Mitesh Dudhat",
              gender: "Male",
              contact_number: "98355434655",
              email_id: "",
              admission_year: "2020",
              merit_12th: "93",
            },
            {
              id: "",
              student_name: "Pinal Patel",
              gender: "Female",
              contact_number: "9978021537",
              email_id: "",
              admission_year: "2021",
              merit_diploma: "93",
            },
          ],
        },

        // <--------------------------------------------------------------fourth Year---------------------------------------------------------->
        {
          year: "Fourth",
          year_head: "D.S. Patil",
          student_data: [
            {
              id: "2019_1",
              student_name: "Nancy Patel",
              gender: "Female",
              contact_number: "9879870013",
              email_id: "nancy@gmail.com",
              admission_year: "2019",
              merit_12th: "77",
            },
            {
              id: "2019_2",
              student_name: "Sankalp Desai",
              gender: "Male",
              contact_number: "9879870014",
              email_id: "sankalp",
              admission_year: "2019",
              merit_12th: "75",
            },
            {
              id: "2019_3",
              student_name: "Sudheer Chouhan",
              gender: "Male",
              contact_number: "9879870015",
              email_id: "sc@gmail.com",
              admission_year: "2019",
              merit_12th: "57",
            },
            {
              id: "2019_4",
              student_name: "Niyati Chawada",
              gender: "Female",
              contact_number: "9879870016",
              email_id: "niyati@gmail.com",
              admission_year: "2019",
              merit_12th: "89",
            },
            {
              id: "",
              student_name: "Megha Chawada",
              gender: "Female",
              contact_number: "9893570016",
              email_id: "",
              admission_year: "2020",
              merit_diploma: "90",
            },
            {
              id: "",
              student_name: "Jyoti Chavda",
              gender: "Female",
              contact_number: "9889870016",
              email_id: "",
              admission_year: "2019",
              merit_12th: "79",
            },
          ],
        },

        // <--------------------------------------------------------------pass year------------------------------------------------------------>
        {
          year: "Pass Out",
          year_head: "Bhavik Patel",
          student_data: [
            {
              id: "2018_1",
              student_name: "Rutu Patel",
              gender: "Female",
              contact_number: "9879870033",
              email_id: "rutu@gmail.com",
              admission_year: "2018",
              merit_12th: "68",
            },
            {
              id: "2018_2",
              student_name: "Charmi Dhudhat",
              gender: "Female",
              contact_number: "9879870034",
              email_id: "charmi@gmail.com",
              admission_year: "2018",
              merit_12th: "87",
            },
            {
              id: "2018_3",
              student_name: "Savi Dravid",
              gender: "Feamle",
              contact_number: "9879870035",
              email_id: "savi@gmail.com",
              admission_year: "2018",
              merit_12th: "91",
            },
            {
              id: "2018_4",
              student_name: "Savi patel",
              gender: "Feamle",
              contact_number: "98723470035",
              email_id: "savi_patel@gmail.com",
              admission_year: "2018",
              merit_12th: "80",
            },
            {
              id: "2018_5",
              student_name: "raxita vaghasiya",
              gender: "Feamle",
              contact_number: "987343470035",
              email_id: "raxita_vaghasiya@gmail.com",
              admission_year: "2018",
              merit_12th: "86",
            },
            {
              id: "",
              student_name: "Dhyey Sharma",
              gender: "Male",
              contact_number: "8141652472",
              email_id: "",
              admission_year: "2018",
              merit_12th: "85",
            },
            {
              id: "",
              student_name: "Shrushti Miyani",
              gender: "Feamle",
              contact_number: "8141652472",
              email_id: "",
              admission_year: "2018",
              merit_12th: "86",
            },
            {
              id: "",
              student_name: "Darshan chopda",
              gender: "Male",
              contact_number: "8148652472",
              email_id: "",
              admission_year: "2018",
              merit_12th: "65",
            },
            {
              id: "2018_6",
              student_name: "Ishan Vekariya",
              gender: "Male",
              contact_number: "9879870036",
              email_id: "ishan@gmail.com",
              admission_year: "2018",
              merit_12th: "78",
            },
          ],
        },
      ],
    },

    // <-----------------------------------------------------------------automobile------------------------------------------------------------>

    {
      department: "Automobile",
      dep_head: "Sachin Tendulkar",
      year: [
        {
          year: "First",
          year_head: "Akhilsh Yadav",
          student_data: [
            {
              id: "2022_1",
              student_name: "Sanket desai",
              gender: "Male",
              contact_number: "9879870017",
              email_id: "sanket@gmail.com",
              admission_year: "2022",
              merit_12th: "67",
            },
            {
              id: "2022_2",
              student_name: "Ram Taneja",
              gender: "Male",
              contact_number: "9879870018",
              email_id: "rt@gmail.com",
              admission_year: "2022",
              merit_12th: "76",
            },
            {
              id: "2022_3",
              student_name: "Vishakha Dhameliya",
              gender: "Feamle",
              contact_number: "9879870019",
              email_id: "vd@gmail.com",
              admission_year: "2022",
              merit_12th: "96",
            },
            {
              id: "2022_4",
              student_name: "Vanshika Tandel",
              gender: "Female",
              contact_number: "9879870020",
              email_id: "vt@gmail.com",
              admission_year: "2022",
              merit_12th: "76",
            },
          ],
        },
        // <--------------------------------------------------------------second year---------------------------------------------------------------------->
        {
          year: "Second",
          year_head: "V.K Shah",
          student_data: [
            {
              id: "2022_0_1",
              student_name: "Parth Patel",
              gender: "Male",
              contact_number: "9879870021",
              email_id: "pp@gmail.com",
              admission_year: "2022",
              merit_diploma: "80",
            },
            {
              id: "2021_2",
              student_name: "Mahi Vaghani",
              gender: "Female",
              contact_number: "9879870022",
              email_id: "mv@gmail.com",
              admission_year: "2021",
              merit_12th: "65",
            },
            {
              id: "2021_3",
              student_name: "Sakshi Bajaj",
              gender: "Female",
              contact_number: "9879870023",
              email_id: "sb@gmail.com",
              admission_year: "2021",
              merit_12th: "87",
            },
            {
              id: "2021_4",
              student_name: "Naveen Shah",
              gender: "Male",
              contact_number: "9879870024",
              email_id: "ns@gmail.com",
              admission_year: "2021",
              merit_12th: "56",
            },
            {
              id: "2021_5",
              student_name: "vairagi dave",
              gender: "Female",
              contact_number: "97398734011",
              email_id: "vairagi_dave@gmail.com",
              admission_year: "2021",
              merit_12th: "93",
            },
            {
              id: "",
              student_name: "Shubham Chauhan",
              gender: "Male",
              contact_number: "54872165478",
              email_id: "",
              admission_year: "2021",
              merit_12th: "85",
            },
            {
              id: "",
              student_name: "Nirav Loriya",
              gender: "Male",
              contact_number: "9721543825",
              email_id: "",
              admission_year: "2021",
              merit_12th: "85",
            },
            {
              id: "",
              student_name: "Nayra Sharma",
              gender: "Feamle",
              contact_number: "34567436654",
              email_id: "",
              admission_year: "2022",
              merit_diploma: "79",
            },
          ],
        },

        // <---------------------------------------------------------------third year---------------------------------------------------------------------->

        {
          year: "Third",
          year_head: "Purvi Tandel",
          student_data: [
            {
              id: "2020_1",
              student_name: "Pinal Nakarani",
              gender: "Female",
              contact_number: "9879870025",
              email_id: "pinal@gmail.com",
              admission_year: "2020",
              merit_12th: "95",
            },
            {
              id: "2020_2",
              student_name: "Chandra Vakani",
              gender: "Male",
              contact_number: "9879870026",
              email_id: "chandra@gmail.com",
              admission_year: "2020",
              merit_12th: "88",
            },
            {
              id: "2020_3",
              student_name: "Vishwas Rav",
              gender: "Male",
              contact_number: "9879870027",
              email_id: "vr@gmail.com",
              admission_year: "2020",
              merit_12th: "78",
            },
            {
              id: "2020_4",
              student_name: "Arvi Khote",
              gender: "Female",
              contact_number: "9879870028",
              email_id: "ak@gmail.com",
              admission_year: "2020",
              merit_12th: "88",
            },
            {
              id: "2021_0_1",
              student_name: "banshi pande",
              gender: "Female",
              contact_number: "92798734011",
              email_id: "banshi_pande@gmail.com",
              admission_year: "2021",
              merit_diploma: "81",
            },
            {
              id: "2021_0_3",
              student_name: "shakshi pande",
              gender: "Female",
              contact_number: "92798734431",
              email_id: "shakshi_pande@gmail.com",
              admission_year: "2021",
              merit_diploma: "83",
            },
            {
              id: "",
              student_name: "Smit Kikani",
              gender: "Male",
              contact_number: "78351564545",
              email_id: "",
              admission_year: "2021",
              merit_diploma: "79",
            },
            {
              id: "",
              student_name: "Divy Patel",
              gender: "Male",
              contact_number: "56536253545",
              email_id: "",
              admission_year: "2020",
              merit_12th: "79",
            },
            {
              id: "",
              student_name: "Yash Undhad",
              gender: "Female",
              contact_number: "4747558555",
              email_id: "",
              admission_year: "2021",
              merit_diploma: "79",
            },
            {
              id: "",
              student_name: "Mayank Mardiya",
              gender: "Male",
              contact_number: "96536343545",
              email_id: "",
              admission_year: "2020",
              merit_12th: "79",
            },
          ],
        },
        // <------------------------------------------------------------forth year----------------------------------------------------------------------->
        {
          year: "Fourth",
          year_head: "Akash Mehata",
          student_data: [
            {
              id: "2019_1",
              student_name: "Rahul Patel",
              gender: "Male",
              contact_number: "9879870029",
              email_id: "rp@gmail.com",
              admission_year: "2019",
              merit_12th: "66",
            },
            {
              id: "2019_2",
              student_name: "Ravindra Dhudhat",
              gender: "Male",
              contact_number: "9879870030",
              email_id: "rd@gmail.com",
              admission_year: "2019",
              merit_12th: "81",
            },
            {
              id: "2019_4",
              student_name: "Sanket Dravid",
              gender: "Male",
              contact_number: "9879870031",
              email_id: "sanket@gmail.com",
              admission_year: "2019",
              merit_12th: "91",
            },
            {
              id: "2019_7",
              student_name: "Shree Vekariya",
              gender: "Female",
              contact_number: "9879870032",
              email_id: "shree@gmail.com",
              admission_year: "2019",
              merit_12th: "78",
            },
            {
              id: "",
              student_name: "Shivam Dravid",
              gender: "Male",
              contact_number: "77567478645",
              email_id: "",
              admission_year: "2019",
              merit_12th: "92",
            },
          ],
        },

        // <---------------------------------------------------------------pass out---------------------------------------------------------------------->

        {
          year: "Pass Out",
          year_head: "Akash Mehata",
          student_data: [
            {
              id: "2018_1",
              student_name: "Anshu Patel",
              gender: "Male",
              contact_number: "9879870037",
              email_id: "anshu@gmail.com",
              admission_year: "2018",
              merit_12th: "76",
            },
            {
              id: "2018_2",
              student_name: "Latika Devani",
              gender: "Female",
              contact_number: "9879870038",
              email_id: "ld@gmail.com",
              admission_year: "2018",
              merit_12th: "81",
            },
            {
              id: "2018_7",
              student_name: "Shekhar Shah",
              gender: "Male",
              contact_number: "9879870039",
              email_id: "ss@gmail.com",
              admission_year: "2018",
              merit_12th: "91",
            },
            {
              id: "2018_4",
              student_name: "Pratik Vekariya",
              gender: "Male",
              contact_number: "9879870040",
              email_id: "pratik@gmail.com",
              admission_year: "2018",
              merit_12th: "78",
            },
            {
              id: "2018_5",
              student_name: "shakshi pande",
              gender: "Female",
              contact_number: "92798734011",
              email_id: "shakshi_pande@gmail.com",
              admission_year: "2018",
              merit_12th: "83",
            },
            {
              id: "",
              student_name: "Harsh Thoriya",
              gender: "Male",
              contact_number: "5465432353652",
              email_id: "",
              admission_year: "2019",
              merit_diploma: "89",
            },
            {
              id: "",
              student_name: "Riya Nakrani",
              gender: "Female",
              contact_number: "56787864553",
              email_id: "",
              admission_year: "2019",
              merit_diploma: "97",
            },
            {
              id: "",
              student_name: "Dushyant Vaja",
              gender: "Male",
              contact_number: "5646456786354",
              email_id: "",
              admission_year: "2019",
              merit_diploma: "96",
            },
          ],
        },
      ],
    },

    // <------------------------------------------------------------------civil---------------------------------------------------------------->

    {
      department: "Civil",
      dep_head: "Virat Kohli",
      year: [
        {
          year: "First",
          year_head: "Nikhil Patel",
          student_data: [
            {
              id: "",
              student_name: "Harsh Patel",
              gender: "Male",
              contact_number: "9879870001",
              email_id: "",
              admission_year: "2022",
              merit_12th: "79",
            },
            {
              id: "",
              student_name: "Jaimin Patel",
              gender: "Male",
              contact_number: "9879870001",
              email_id: "",
              admission_year: "2022",
              merit_12th: "96",
            },
            {
              id: "",
              student_name: "Jeet Vasava",
              gender: "Male",
              contact_number: "9879870001",
              email_id: "",
              admission_year: "2022",
              merit_12th: "81",
            },
            {
              id: "2022_2",
              student_name: "Shalini Patel",
              gender: "Female",
              contact_number: "9879870002",
              email_id: "pshalini@gmail.com",
              admission_year: "2022",
              merit_12th: "85",
            },
            {
              id: "2022_3",
              student_name: "Kevin jadeja",
              gender: "Male",
              contact_number: "9879870003",
              email_id: "kevin@gmail.com",
              admission_year: "2022",
              merit_12th: "87",
            },
            {
              id: "2022_4",
              student_name: "Harsh Dhorajiya",
              gender: "Male",
              contact_number: "9879870004",
              email_id: "Harsh22@gmail.com",
              admission_year: "2022",
              merit_12th: "83",
            },
            {
              id: "",
              student_name: "Vishal Gajera",
              gender: "Male",
              contact_number: "9835540004",
              email_id: "",
              admission_year: "2022",
              merit_12th: "93",
            },
          ],
        },

        // <-------------------------------------------------------------second year---------------------------------------------------------->

        {
          year: "Second",
          year_head: "Jagdish Vasava",
          student_data: [
            {
              id: "",
              student_name: "Jatin Panchal",
              gender: "Male",
              contact_number: "9879870006",
              email_id: "",
              admission_year: "2022",
              merit_diploma: "57",
            },
            {
              id: "",
              student_name: "Kishan Vasani",
              gender: "Male",
              contact_number: "9879870006",
              email_id: "",
              admission_year: "2022",
              merit_diploma: "68",
            },
            {
              id: "2021_1",
              student_name: "Divayesh Ranpara",
              gender: "Male",
              contact_number: "9879870005",
              email_id: "dr@gmail.com",
              admission_year: "2021",
              merit_12th: "78",
            },
            {
              id: "",
              student_name: "Yagnik Devani",
              gender: "Male",
              contact_number: "9879870008",
              email_id: "",
              admission_year: "2021",
              merit_12th: "88",
            },
            {
              id: "",
              student_name: "Ronak Koladiya",
              gender: "Male",
              contact_number: "9879870008",
              email_id: "",
              admission_year: "2021",
              merit_12th: "80",
            },
            {
              id: "2022_0_2",
              student_name: "Krunal Mehata",
              gender: "Male",
              contact_number: "9879870006",
              email_id: "Krunal23@gmail.com",
              admission_year: "2022",
              merit_diploma: "88",
            },
            {
              id: "2022_0_4",
              student_name: "Shubham Khunt",
              gender: "Male",
              contact_number: "9879870007",
              email_id: "shubhu7@gmail.com",
              admission_year: "2022",
              merit_diploma: "67",
            },
            {
              id: "",
              student_name: "Bhargav Gajera",
              gender: "Male",
              contact_number: "9835540004",
              email_id: "",
              admission_year: "2021",
              merit_12th: "93",
            },
            {
              id: "2021_2",
              student_name: "Ashwin Patel",
              gender: "Male",
              contact_number: "9879870008",
              email_id: "apatel@gmail.com",
              admission_year: "2021",
              merit_12th: "77",
            },
          ],
        },

        // <-------------------------------------------------------------third year----------------------------------------------------------->

        {
          year: "Third",
          year_head: "Bharat Parmar",
          student_data: [
            {
              id: "2021_0_1",
              student_name: "Chitranjan Rama",
              gender: "Male",
              contact_number: "9879870009",
              email_id: "c.r@gmail.com",
              admission_year: "2021",
              merit_diploma: "72",
            },
            {
              id: "2020_2",
              student_name: "Nupur Parmer",
              gender: "Female",
              contact_number: "9879870010",
              email_id: "np@gmail.com",
              admission_year: "2020",
              merit_12th: "77",
            },
            {
              id: "2020_3",
              student_name: "Sameera Rai",
              gender: "Female",
              contact_number: "9879870011",
              email_id: "sameera@gmail.com",
              admission_year: "2020",
              merit_12th: "88",
            },
            {
              id: "2020_4",
              student_name: "Prabhat Goda",
              gender: "Male",
              contact_number: "9879870012",
              email_id: "pg@gmail.com",
              admission_year: "2020",
              merit_12th: "65",
            },
            {
              id: "2021_0_2",
              student_name: "Vaishali Bhatt",
              gender: "Female",
              contact_number: "98798734011",
              email_id: "Vaishali_bhatt@gmail.com",
              admission_year: "2021",
              merit_diploma: "74",
            },
            {
              id: "",
              student_name: "Mitesh Dudhat",
              gender: "Male",
              contact_number: "98355434655",
              email_id: "",
              admission_year: "2020",
              merit_12th: "93",
            },
            {
              id: "",
              student_name: "Pinal Patel",
              gender: "Female",
              contact_number: "9978021537",
              email_id: "",
              admission_year: "2021",
              merit_diploma: "93",
            },
          ],
        },

        // <--------------------------------------------------------------fourth Year---------------------------------------------------------->

        {
          year: "Fourth",
          year_head: "Himanshu Shah",
          student_data: [
            {
              id: "2019_1",
              student_name: "Nancy Patel",
              gender: "Female",
              contact_number: "9879870013",
              email_id: "nancy@gmail.com",
              admission_year: "2019",
              merit_12th: "77",
            },
            {
              id: "2019_2",
              student_name: "Sankalp Desai",
              gender: "Male",
              contact_number: "9879870014",
              email_id: "sankalp",
              admission_year: "2019",
              merit_12th: "75",
            },
            {
              id: "2019_3",
              student_name: "Sudheer Chouhan",
              gender: "Male",
              contact_number: "9879870015",
              email_id: "sc@gmail.com",
              admission_year: "2019",
              merit_12th: "57",
            },
            {
              id: "2019_4",
              student_name: "Niyati Chawada",
              gender: "Female",
              contact_number: "9879870016",
              email_id: "niyati@gmail.com",
              admission_year: "2019",
              merit_12th: "89",
            },
            {
              id: "",
              student_name: "Megha Chawada",
              gender: "Female",
              contact_number: "9893570016",
              email_id: "",
              admission_year: "2020",
              merit_diploma: "90",
            },
            {
              id: "",
              student_name: "Jyoti Chavda",
              gender: "Female",
              contact_number: "9889870016",
              email_id: "",
              admission_year: "2019",
              merit_12th: "79",
            },
          ],
        },

        // <--------------------------------------------------------------pass year------------------------------------------------------------>

        {
          year: "Pass Out",
          year_head: "Dipak Jadeja",
          student_data: [
            {
              id: "2018_1",
              student_name: "Rutu Patel",
              gender: "Female",
              contact_number: "9879870033",
              email_id: "rutu@gmail.com",
              admission_year: "2018",
              merit_12th: "68",
            },
            {
              id: "2018_2",
              student_name: "Charmi Dhudhat",
              gender: "Female",
              contact_number: "9879870034",
              email_id: "charmi@gmail.com",
              admission_year: "2018",
              merit_12th: "87",
            },
            {
              id: "2018_3",
              student_name: "Savi Dravid",
              gender: "Feamle",
              contact_number: "9879870035",
              email_id: "savi@gmail.com",
              admission_year: "2018",
              merit_12th: "91",
            },
            {
              id: "2018_4",
              student_name: "Savi patel",
              gender: "Feamle",
              contact_number: "98723470035",
              email_id: "savi_patel@gmail.com",
              admission_year: "2018",
              merit_12th: "80",
            },
            {
              id: "2018_5",
              student_name: "raxita vaghasiya",
              gender: "Feamle",
              contact_number: "987343470035",
              email_id: "raxita_vaghasiya@gmail.com",
              admission_year: "2018",
              merit_12th: "86",
            },
            {
              id: "",
              student_name: "Dhyey Sharma",
              gender: "Male",
              contact_number: "8141652472",
              email_id: "",
              admission_year: "2018",
              merit_12th: "85",
            },
            {
              id: "",
              student_name: "Shrushti Miyani",
              gender: "Feamle",
              contact_number: "8141652472",
              email_id: "",
              admission_year: "2018",
              merit_12th: "86",
            },
            {
              id: "",
              student_name: "Darshan chopda",
              gender: "Male",
              contact_number: "8148652472",
              email_id: "",
              admission_year: "2018",
              merit_12th: "65",
            },
            {
              id: "2018_6",
              student_name: "Ishan Vekariya",
              gender: "Male",
              contact_number: "9879870036",
              email_id: "ishan@gmail.com",
              admission_year: "2018",
              merit_12th: "78",
            },
          ],
        },
      ],
    },
  ],
};

data.department_data.map((departmentitem) => {
  const dep_head = departmentitem.dep_head;
  const department = departmentitem.department;

  departmentitem.year.forEach((years) => {
    var arraylistofmerit12th = [];
    var arraylistofmeritdiploma = [];
    const year = years.year;
    const year_head = years.year_head;
    years.student_data.forEach((students) => {
      if (Object.keys(students).some((e) => e.includes("merit_12th"))) {
       
        arraylistofmerit12th.push(
          parseInt(students.id.charAt(students.id.length -1))
        );
        if (!students.id) {
          // arraylistofmerit12th.forEach((e) => {});
          // console.log(arraylistofmerit12th);
          
            for (var i = 1; i <= arraylistofmerit12th.length+1; i++) {
              if (!arraylistofmerit12th.includes(i)) {
                students.id = `${students.admission_year}_${i}`;
                let nanIndex = arraylistofmerit12th.findIndex(value => isNaN(value));
                arraylistofmerit12th[nanIndex] = i; 
                // console.log(arraylistofmerit12th);
              }
            }
        }
      } else if (
        Object.keys(students).some((e) => e.includes("merit_diploma"))
      ) {
        arraylistofmeritdiploma.push(students.id);
        if (!students.id) {
          for (var j = 0; j < arraylistofmeritdiploma.length; j++) {
            for (var i = 1; i <= arraylistofmeritdiploma.length; i++) {
              if (arraylistofmeritdiploma[j] != i) {
                students.id = `2022_0_${i}`;
              }
            }
          }
        }
      }
    });
  });
});

